dist: focal

language: go

go:
- 1.20

services:
- docker

before_install:
- go install github.com/mattn/goveralls@latest
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
- source "${HOME}/google-cloud-sdk/path.bash.inc"
- if [[ -n "$SERVICE_ACCOUNT_mlab_testing" ]] ; then
  echo "$SERVICE_ACCOUNT_mlab_testing" > $TRAVIS_BUILD_DIR/creds.json ;
  export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/creds.json ;
  echo "TESTING CREDS FOUND" ;
  else echo "NO TESTING CREDS FOUND" ;
  fi

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

script:
# This assumes we never have a file named __coverage.cov checked in. A
# good assumption, but one we should note.
- GCLOUD_PROJECT=mlab-testing
    go test -v -covermode=count -coverprofile=__coverage.cov -coverpkg=./... ./...
- $HOME/gopath/bin/goveralls -coverprofile=__coverage.cov -service=travis-ci
- docker build -t pushertest .
- mkdir fakedata;
    docker run
      -v `pwd`/fakedata:/var/spool/fakedata
      -v $TRAVIS_BUILD_DIR:/creds
      -e GOOGLE_APPLICATION_CREDENTIALS=/creds/creds.json
      pushertest --dry_run --directory /var/spool --datatype fakedata=1
